from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from itertools import combinations
from pathlib import Path
from typing import Any

import pandas as pd

import backtest as bt
import research_runtime as rr
from research_pair_registry import PAIR_RESEARCH_REGISTRY, PairResearchPlan


RESULTS_DIR = Path("results")
CACHE_DIR = Path("data_cache_walkforward")
DEFAULT_TARGET_PAIRS = 5
COMMISSION_PCT = 0.0026
SLIPPAGE_PCT = 0.0005


def _load_json_candidates(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    with open(path, "r", encoding="utf-8") as handle:
        return list(json.load(handle))


def _plan_key(plan: PairResearchPlan) -> tuple[str, str, str, str]:
    return (plan.pair, plan.construction, plan.entry_filter, plan.exit_profile)


def _load_history(pair: str, history_days: int) -> pd.DataFrame | None:
    cache_path = CACHE_DIR / f"{pair}_15m_{history_days}d_uniform_live.csv"
    if not cache_path.exists():
        return None
    df = pd.read_csv(cache_path)
    df.columns = [column.lower() for column in df.columns]
    if "timestamp" in df.columns:
        df = df.rename(columns={"timestamp": "ts"})
    if "vwap_k" not in df.columns:
        df["vwap_k"] = (df["open"] + df["high"] + df["low"] + df["close"]) / 4
    if "count" not in df.columns:
        df["count"] = 1
    return df.sort_values("ts").reset_index(drop=True)


def _summarize(trades: list[bt.BacktestTrade]) -> dict[str, Any]:
    if not trades:
        return {
            "trades": 0,
            "net_pct": 0.0,
            "win_rate": 0.0,
            "avg_trade_pct": 0.0,
            "max_dd_pct": 0.0,
        }
    pnls = pd.Series([trade.pnl_pct for trade in trades], dtype=float)
    equity = (1.0 + pnls).cumprod()
    return {
        "trades": int(len(trades)),
        "net_pct": float(pnls.sum()),
        "win_rate": float((pnls > 0).mean()),
        "avg_trade_pct": float(pnls.mean()),
        "max_dd_pct": float((equity / equity.cummax() - 1.0).min()),
    }


def _window_summaries(
    trades: list[bt.BacktestTrade],
    max_ts: int,
) -> dict[str, dict[str, Any]]:
    recent30_start = max_ts - 30 * 24 * 60 * 60 if max_ts else 0
    recent14_start = max_ts - 14 * 24 * 60 * 60 if max_ts else 0
    return {
        "full": _summarize(trades),
        "recent30": _summarize([trade for trade in trades if trade.entry_ts >= recent30_start]),
        "recent14": _summarize([trade for trade in trades if trade.entry_ts >= recent14_start]),
    }


def _portfolio_score(summary120: dict[str, Any], summary60: dict[str, Any]) -> float:
    stats120 = summary120["full"]
    stats60 = summary60["full"]
    stats30 = summary120["recent30"]
    stats14 = summary120["recent14"]

    floor = min(
        stats120["net_pct"],
        stats60["net_pct"],
        stats30["net_pct"],
        stats14["net_pct"],
    )
    return (
        1.00 * stats120["net_pct"]
        + 1.00 * stats60["net_pct"]
        + 0.75 * stats30["net_pct"]
        + 0.25 * stats14["net_pct"]
        + 0.50 * floor
        - 0.35 * abs(stats120["max_dd_pct"])
        - 0.25 * abs(stats60["max_dd_pct"])
    )


def _candidate_sources() -> dict[str, list[PairResearchPlan]]:
    sources: dict[str, list[PairResearchPlan]] = {}

    # Current registry plans always remain candidate options.
    for plan in PAIR_RESEARCH_REGISTRY.values():
        if plan.status == "drop":
            continue
        sources.setdefault(plan.pair, []).append(plan)

    # Shadow/portfolio sweep candidates.
    for item in _load_json_candidates(RESULTS_DIR / "sweep_candidates.json"):
        plan = PairResearchPlan(
            pair=str(item["pair"]).upper(),
            construction=str(item["construction"]),
            entry_filter=str(item["entry_filter"]),
            exit_profile=str(item["exit_profile"]),
            status="candidate",
            note="Generated by densified pair sweep.",
        )
        sources.setdefault(plan.pair, []).append(plan)

    # Active repair sweep candidates.
    for item in _load_json_candidates(RESULTS_DIR / "active_sweep_candidates.json"):
        plan = PairResearchPlan(
            pair=str(item["pair"]).upper(),
            construction=str(item["construction"]),
            entry_filter=str(item["entry_filter"]),
            exit_profile=str(item["exit_profile"]),
            status="candidate",
            note="Generated by densified active-pair repair sweep.",
        )
        sources.setdefault(plan.pair, []).append(plan)

    # Deduplicate per pair.
    deduped: dict[str, list[PairResearchPlan]] = {}
    for pair, plans in sources.items():
        seen: set[tuple[str, str, str, str]] = set()
        deduped[pair] = []
        for plan in plans:
            key = _plan_key(plan)
            if key in seen:
                continue
            seen.add(key)
            deduped[pair].append(plan)
    return deduped


def _precompute_trades(
    candidates_by_pair: dict[str, list[PairResearchPlan]],
    history_days: int,
) -> tuple[dict[tuple[str, str, str, str], list[bt.BacktestTrade]], int]:
    trade_map: dict[tuple[str, str, str, str], list[bt.BacktestTrade]] = {}
    max_ts = 0
    for pair, plans in candidates_by_pair.items():
        df_raw = _load_history(pair, history_days)
        if df_raw is None or df_raw.empty:
            continue
        max_ts = max(max_ts, int(df_raw["ts"].iloc[-1]))
        for plan in plans:
            key = _plan_key(plan)
            if key in trade_map:
                continue
            frame = rr.build_research_frame(df_raw, plan)
            trades = bt.run_backtest_frame(
                pair=pair,
                df=frame,
                config=rr.config_for_plan(plan),
                commission_pct=COMMISSION_PCT,
                slippage_pct=SLIPPAGE_PCT,
                construction=plan.construction,
            )
            trade_map[key] = trades
    return trade_map, max_ts


def _combine_trades(
    plans: list[PairResearchPlan],
    trade_map: dict[tuple[str, str, str, str], list[bt.BacktestTrade]],
) -> list[bt.BacktestTrade]:
    trades: list[bt.BacktestTrade] = []
    for plan in plans:
        trades.extend(trade_map.get(_plan_key(plan), []))
    return trades


def optimize_book(
    target_pairs: int,
    top_k: int,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    candidates_by_pair = _candidate_sources()
    trade_map_120, max_ts_120 = _precompute_trades(candidates_by_pair, 120)
    trade_map_60, max_ts_60 = _precompute_trades(candidates_by_pair, 60)

    locked_pairs = [
        plan for plan in PAIR_RESEARCH_REGISTRY.values()
        if plan.status in {"active_frozen", "active"}
    ]
    locked_pair_names = {plan.pair for plan in locked_pairs}

    optional_pool: list[PairResearchPlan] = []
    for pair, plans in candidates_by_pair.items():
        if pair in locked_pair_names:
            continue
        optional_pool.extend(plans)

    slots = max(0, target_pairs - len(locked_pairs))
    if slots == 0:
        raise ValueError("target_pairs leaves no room for optional slots")

    scored: list[dict[str, Any]] = []
    for combo in combinations(optional_pool, slots):
        combo_pairs = [plan.pair for plan in combo]
        if len(set(combo_pairs)) != len(combo_pairs):
            continue
        roster = [*locked_pairs, *combo]
        trades120 = _combine_trades(roster, trade_map_120)
        trades60 = _combine_trades(roster, trade_map_60)
        summary120 = _window_summaries(trades120, max_ts_120)
        summary60 = _window_summaries(trades60, max_ts_60)

        if summary120["full"]["net_pct"] <= 0:
            continue
        if summary60["full"]["net_pct"] <= 0:
            continue
        if summary120["recent30"]["net_pct"] < 0:
            continue

        scored.append(
            {
                "score": _portfolio_score(summary120, summary60),
                "roster": [asdict(plan) for plan in roster],
                "summary120": summary120,
                "summary60": summary60,
            }
        )

    scored.sort(key=lambda row: row["score"], reverse=True)

    baseline_roster = list(locked_pairs)
    current_optional = [
        plan for plan in PAIR_RESEARCH_REGISTRY.values()
        if plan.status == "active_experimental"
    ]
    baseline_roster.extend(current_optional)
    baseline120 = _window_summaries(_combine_trades(baseline_roster, trade_map_120), max_ts_120)
    baseline60 = _window_summaries(_combine_trades(baseline_roster, trade_map_60), max_ts_60)
    baseline = {
        "roster": [asdict(plan) for plan in baseline_roster],
        "summary120": baseline120,
        "summary60": baseline60,
        "score": _portfolio_score(baseline120, baseline60),
    }

    return scored[:top_k], baseline


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Multi-window densified optimizer for the research book.",
    )
    parser.add_argument("--target-pairs", type=int, default=DEFAULT_TARGET_PAIRS)
    parser.add_argument("--top-k", type=int, default=10)
    parser.add_argument(
        "--out-json",
        default="results/book_optimizer_rosters.json",
    )
    parser.add_argument(
        "--out-csv",
        default="results/book_optimizer_top.csv",
    )
    args = parser.parse_args()

    top_rosters, baseline = optimize_book(
        target_pairs=args.target_pairs,
        top_k=args.top_k,
    )

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    with open(args.out_json, "w", encoding="utf-8") as handle:
        json.dump({"baseline": baseline, "top_rosters": top_rosters}, handle, indent=2)

    csv_rows: list[dict[str, Any]] = []
    for idx, roster in enumerate(top_rosters, start=1):
        csv_rows.append(
            {
                "rank": idx,
                "score": roster["score"],
                "pairs": ",".join(item["pair"] for item in roster["roster"]),
                "plans": " | ".join(
                    f"{item['pair']}:{item['construction']}/{item['entry_filter']}/{item['exit_profile']}"
                    for item in roster["roster"]
                ),
                "full120_trades": roster["summary120"]["full"]["trades"],
                "full120_net_pct": roster["summary120"]["full"]["net_pct"],
                "full120_max_dd_pct": roster["summary120"]["full"]["max_dd_pct"],
                "full60_trades": roster["summary60"]["full"]["trades"],
                "full60_net_pct": roster["summary60"]["full"]["net_pct"],
                "recent30_net_pct": roster["summary120"]["recent30"]["net_pct"],
                "recent14_net_pct": roster["summary120"]["recent14"]["net_pct"],
            }
        )

    pd.DataFrame(csv_rows).to_csv(args.out_csv, index=False)

    print("BOOK OPTIMIZER")
    print(
        f"baseline: 120d={baseline['summary120']['full']['net_pct']:+.4%} "
        f"60d={baseline['summary60']['full']['net_pct']:+.4%} "
        f"recent30={baseline['summary120']['recent30']['net_pct']:+.4%} "
        f"score={baseline['score']:+.6f}"
    )
    for row in csv_rows[:5]:
        print(
            f"#{row['rank']} score={row['score']:+.6f} "
            f"120d={row['full120_net_pct']:+.4%} "
            f"60d={row['full60_net_pct']:+.4%} "
            f"recent30={row['recent30_net_pct']:+.4%} "
            f"pairs={row['pairs']}"
        )


if __name__ == "__main__":
    main()
